name: Build
on: [ push, pull_request ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        output: 
        # Drawbridge
        - nixosConfigurations.store-staging.config.system.build.toplevel
        - nixosConfigurations.store-testing.config.system.build.toplevel
        - nixosConfigurations.store.config.system.build.toplevel

        # Steward
        - nixosConfigurations.attest-staging.config.system.build.toplevel
        - nixosConfigurations.attest-testing.config.system.build.toplevel
        - nixosConfigurations.attest.config.system.build.toplevel

        # Benefice
        - nixosConfigurations.sgx-equinix-try.config.system.build.toplevel
        - nixosConfigurations.snp-equinix-try.config.system.build.toplevel

        # CI
        - nixosConfigurations.nuc-1-ci.config.system.build.toplevel

        os:
        - ubuntu-20.04
        - macos-latest

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: enarx
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build ${{ matrix.output }}
      run: nix build -L '.#${{ matrix.output }}'

    # TODO: Build and run a VM, test
