name: Lint
on: [ push, pull_request ]
jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v17
    - name: nix flake check
      run: nix flake check
    - name: nix fmt
      run: nix fmt ./flake.nix ./shell.nix
